version: '3.8'

services:
  questions-answers:
    build: .
    container_name: questions-answers
    ports:
      - 8080:8080
    networks:
      - questions-answers-net
    volumes:
      - questions-answers-data:/var/lib/questions-answers/public

  mongo:
    image: mongo:6.0.4
    container_name: mongo
    networks:
      - questions-answers-net
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7.0.8-alpine
    container_name: redis
    networks:
      - questions-answers-net

networks:
  questions-answers-net:
    name: questions-answers-net

volumes:
  questions-answers-data:
    name: questions-answers-net
  
  mongo-data:
    name: mongo-data